// This file is automatically generated
package com.google.livingstories.client.lsp;

/**
 * Interface to represent the messages contained in resource bundle:
 * 	LspMessages.properties'.
 */
public interface LspMessages extends com.google.gwt.i18n.client.Messages {
  
  /**
   * Translated "{0} to {1} ".
   * 
   * @return translated "{0} to {1} "
   */
  @DefaultMessage("{0} to {1} ")
  @Key("dateRange")
  String dateRange(String arg0,  String arg1);

  /**
   * Translated "RSS Feed for {0}".
   * 
   * @return translated "RSS Feed for {0}"
   */
  @DefaultMessage("RSS Feed for {0}")
  @Key("rssFeedTitle")
  String rssFeedTitle(String arg0);

  /**
   * Translated "{0} to {1}".
   * 
   * @return translated "{0} to {1}"
   */
  @DefaultMessage("{0} to {1}")
  @Key("timeRange")
  String timeRange(String arg0,  String arg1);
}
