// This file is automatically generated
package com.google.livingstories.client.contentmanager;

/**
 * Interface to represent the constants contained in resource bundle:
 * 	'ContentManagerConstants.properties'.
 */
public interface ContentManagerConstants extends com.google.gwt.i18n.client.Constants {
  
  /**
   * Translated "No results".
   * 
   * @return translated "No results"
   */
  @DefaultStringValue("No results")
  @Key("noSearchResults")
  String noSearchResults();
}
